// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meucachorro.Repositorio.Migrations
{
    [DbContext(typeof(MeucachorroContexto))]
    [Migration("20250411201751_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meucachorro.Dominio.Entidades.Animal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnimalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Achado")
                        .HasColumnType("bit")
                        .HasColumnName("Achado");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataPerdido")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataPerdido");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Especie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Raca");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UrlImagem");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Animal", (string)null);
                });

            modelBuilder.Entity("Meucachorro.Dominio.Entidades.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConsultaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalID")
                        .HasColumnType("int")
                        .HasColumnName("AnimalID");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataConsulta");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.Property<int>("TipoConsultaID")
                        .HasColumnType("int")
                        .HasColumnName("TipoConsultaID");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id")
                        .HasName("PK_Consulta");

                    b.HasIndex("AnimalID");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("DataConsulta", "AnimalID")
                        .HasDatabaseName("IX_Consulta_Data_Animal");

                    b.ToTable("Consulta", (string)null);
                });

            modelBuilder.Entity("Meucachorro.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SenhaHash");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefone");

                    b.Property<int>("TipoUsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("TipoUsuarioID");

                    b.HasKey("ID");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Meucachorro.Dominio.Entidades.Animal", b =>
                {
                    b.HasOne("Meucachorro.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Animal")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meucachorro.Dominio.Entidades.Consulta", b =>
                {
                    b.HasOne("Meucachorro.Dominio.Entidades.Animal", "Animal")
                        .WithMany("Consultas")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meucachorro.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Consultas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Meucachorro.Dominio.Entidades.Animal", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Meucachorro.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Animal");

                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
